apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-intra-namespace
  namespace: {{ .Release.Namespace }} 
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["{{ .Release.Namespace }}"]
