apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: standard-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      monitoring: standard
  namespaceSelector:
    matchNames:
      - {{ .Values.serviceMonitors.standard.namespace }}
  endpoints:
    - port: {{ .Values.serviceMonitors.standard.port }}
      path: {{ .Values.serviceMonitors.standard.path }}
      interval: {{ .Values.serviceMonitors.standard.interval }}
