apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: standard-service-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      monitoring: standard
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
