apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
spec:
  selector:
    matchLabels:
      app: istiod
  namespaceSelector:
    matchNames:
      - {{ .Values.monitors.istio.namespace }}
  endpoints:
  - port: {{ .Values.monitors.istio.istiod.port }}
    interval: {{ .Values.monitors.default.interval }}
